version: '3.7'

services:
  minimalism-service-redis:
    container_name: minimalism-service-redis
    image: carlonicora/minimalism-service-redis:2.0.0
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
      args:
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
    working_dir: /app
    volumes:
      - ../:/app
      - ../:/opt/project
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora